{% set version = "0.0.21" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppspdlog
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppSpdlog_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppSpdlog/RcppSpdlog_{{ version }}.tar.gz
  sha256: 6ef62d3c4d87334c9c83d81449d85009497163163f19f87227bfb8792e533c69

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('RcppSpdlog')"           # [not win]
    - "\"%R%\" -e \"library('RcppSpdlog')\""  # [win]

about:
  home: https://dirk.eddelbuettel.com/code/rcpp.spdlog.html
  dev_url: https://github.com/eddelbuettel/rcppspdlog
  license: GPL-2.0-or-later
  summary: The mature and widely-used C++ logging library 'spdlog' by Gabi Melman provides many desirable features. This package bundles these header files for easy use by R packages via a simple 'LinkingTo:' inclusion.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - raivivek
